
/**语言包  cn: 中文包；en：英文包；ja：日文包*/
var cn = {
    //index.html
    item_title2 : '开发工具发布',
    item_title3 : '基于区块链透明自治的游戏生态一站闭环的',
    item_title4 : '“共享”共有的公共社区',
    item_btn1 : '白皮书',
    item_btn2 : '源代码',
    c2_index_h2 : '案例展示',
    c2_index_title : 'BCreator开发工具发布',
    c2_index_title1 : '第一期销售BCreator license采用推荐人制，' + '<br>' + '购买者需通过邀请码激活获得购买资格。',
    //c2_index_title2 : '购买者需通过邀请码激活获得购买资格。',
    c2_index_content0 : '中国创造的3D HTML5云引擎',
    c2_index_content1 : '开发者可通过BCreator创作3D/VR/AR/MR内容，' + '<br>' + '并应用到游戏、军事、旅游、电商、教育等领域。',
    c2_index_content2 : '《真三国战记》',
    c2_index_content3 : '首款全视角、电影级动作效果的3D H5游戏',
    c2_index_content4 : '《全面回忆》',
    c2_index_content5 : '斩获ChinaJoy金翎奖及出版总署十强奖的3D次时代游戏',
    c2_index_content6 : '《军事VR》',
    c2_index_content7 : '国家相关机构指定的3D/VR引擎',
    language_version : '中文',

    //login.html
    ltitle_text1 : '电子邮件',
    ltitle_text2 : '密码',
    login_btn : '登录',
    forget_password : '忘记密码',
    register_account : '注册账号',
    //registered.html
    rtitle_text1 : '电子邮件',
    rtitle_text2 : '密码',
    rtitle_text3 : '确认密码',
    rtitle_text4 : '邀请码',
    rtitle_text5 : '关于邀请制',
    register_btn : '注册',
    rto_login : '登录',
    find_detail : '查看详情',
    invite_password_text: '参与GAME.FUND社区需通过邀请码验证，详情请见邀请制说明',
    //forget_psw.html
    ftitle_text : '电子邮件',
    email_btn : '发送邮件',
    fto_login : '登录',
    forget_password_text: '请填入您注册时使用的电子邮箱，您将会收到关于如何重置密码的电子邮件提示。',
    //get_qualified.html
    gtop_half_text2 : '获得购买登记资格，而获得资格的用户也可以将获得',
    gtop_half_text3 : '的Kiss积分购买社区邀请码赠送好友。',
    gbottom_input_title : '请输入邀请码激活身份',
    gbottom_input : '请输入邀请码',
    gconfirm_activation : '确认激活',
    gsuccessful_title : '激活成功',
    gsuccessfull_text1 : '恭喜您获得购买开发工具',
    gsuccessfull_text2 : 'BCreator license的登记名额',
    gactivation_successful_confirm : '确认',
    //already_get_qualified.html
    abottom_input_title : '请输入你要邀请人的姓名',
    invited_name_input : '请输入邀请人姓名',
    aconfirm_activation : '生成邀请码',
    share_tips : '分享提示：长按图片保存或分享',
    //buy.html
    currency_item_title : '请选择支付币种',
    wallet_item_title : '请输入上一步选择支付币种的支付账号',
    num_item_title : '请输入计划购买BCreator license的数量',
    need_pay_num : '需支付',
    bsuccessful_title : '登记成功！',
    bsuccessfull_text : '请进入我的订单查看详情。',
    bactivation_successful_confirm : '确认',
    //my_order.html
    order_title : '我的订单',
    //my_invitation.html
    invitation_title : '邀请统计',
    statistics_title1 : '总共',
    statistics_title2 : '已使用',
    statistics_title3 : '已失效',
    show_available : '可使用',
    show_used : '已使用',
    //my_income.html
    income_title : '我的收益',
    //head.js
    download_app : 'APP下载',
    my_order : '我的订单',
    my_invitation : '邀请统计',
    my_income : '我的收益',
    loginout : '注销登录',
    //foot.js
    index_btn : '项目介绍',
    getQualified : '获取资格',
    please_gqualified : '请先获取资格!',
    //index.js
    please_downloadapp : '请点击APP下载，进行游戏体验！',
    //already_get_qualified.js
    generate_fail : '生成失败！',
    operate_error : '操作异常，请重新操作！',
    not_fill_name : '邀请人姓名未填写！',
    fill_text1 : '基于区块链透明自治的游戏生态一站闭环的',
    fill_text2 : '“共享”共有的公共社区',
    fill_text3 : '在获取资格页面输入邀请码，可申请获得购买软件的登记名额',
    //buy.js
    infor_fill : '资料填写错误或者不全！',
    fill_right_email : '请输入正确的邮箱地址',
    //forget_psw.js
    send_success : '发送成功，请登录邮箱修改密码',
    send_fail : '发送失败',
    //get_qualified.js
    fill_code : '请输入邀请码',
    un_code : '无效的邀请码！',
    code_used : '邀请码已被使用！',
    expried_code : '邀请码已过期！',
    user_invited : '用户已经被邀请，无法重复绑定！',
    //login.js
    login_error : '账号不存在或者密码错误！',
    //my_income.js
    no_more_sum : '没有更多数据',
    //my_invitation.js
    will_to : '将于',
    expried : '过期',
    //my_order.js
    waite_ex : '等待支付',
    under_review : '审核中',
    deal_success : '交易成功',
    o_expreid : '已失效',
    status_exception : '状态异常',
    buy_sum : '购买数量：',
    need_pay : '需支付',
    tradeno : '订单号：',
    find_detail : '查看详情',
    pay_info : '支付信息：',
    collect_money : '收款钱包账号',
    trade_info : '订单信息：',
    product_name : '产品名称：',
    product_num : '产品数量：',
    need_pay_money : '所需支付金额：',
    pay_num : '付款钱包账号：',
    trade_time : '订单生成时间：',
    trade_status : '订单状态：',
    //register.js
    inspect : '请核对信息确认无误后再提交!',
    number_error : '账号不存在或者密码错误！',
    number_exist : '账户已经存在！',
    redister_fail : '注册失败！',
    system_req : '至少7位字符，包含数字和字母，不含空格',
    fill_pwd : '您必须输入匹配的密码',
    //新变动1
    buy_btn : '预登记',
    gtop_half_title : '为什么需要邀请码？',
    gtop_half_text1 : '参与GAME.FUND社区名额采用推荐人制，参与者需通过邀请码激活身份，获得参与资格。',
    gbottom_half_title : '如何获得邀请码？',
    gbottom_half_text_ul_p1 : '向已获得资格的用户索要邀请码，获得资格用户有权限生成。',
    gbottom_half_text_ul_p2 : '请联系社区理事会，邮箱：info@game.fund',
    already_registration : '你已预登记过',
    atop_half_title1 : '帮助他人获得参与',
    atop_half_title2 : '社区的资格',
    abottom_half_title1 : '邀请好友加入',
    abottom_half_title2 : 'G',
    abottom_half_title3 : 'AME.',
    abottom_half_title4 : 'F',
    abottom_half_title5 : 'UND',
    rtitle_text4 : '邀请码',

    //新变动2.1
    account_login : '账号登录',
    account_register : '账号注册',
    password_find : '密码找回',
    joinWhitelist : '加入白名单',
    pleaseReadStmt : '请先阅读协议并接受后，再注册',
    fill_email_length : '邮箱地址不能超过50个字符',
    password_length : '密码长度不能超过50个字符',
    readAccept : '阅读并接受',
    serverList : '服务条款',
    getInvitationBtn : '生成邀请码',
    registerSuccess : '账号注册成功！',
    joinGAME : '是否加入Game.Fund白名单？',
    continueBtn : '加入', 
    // atop_half_text1 : '参与GAME.FUND社区名额采用社区内推荐人制，注册社区账号需通过社区邀请码验证。推荐人将获得被推荐人购买GF通证总量的5%GF通证奖励。',
    atop_half_text2 : '社区账号需通过社区邀请码验证。推荐人将获得',
    atop_half_text3 : '被推荐人购买GF通证总量的5%GF通证奖励。',
    my_reward : '我的奖励',
    buy_tip_title1_1 : '加入',
    buy_tip_title1_2 : '白名单',
    importent_tip : '重要提示',
    buy_top_text1 : '白名单人员一旦达到最大数量，加入白名单通道将关闭。我们将通过官方telegram公告群以及邮件通知到您。',

    buy_tips_1 : 'GAME.FUND',
    buy_tips_2 : 'GF通证认购白名单',
    buy_tips_text1 : '我们正在为我们的社区创建一份白名单。您从第一天就一直与我们在一起，我们希望确保您可以在我们的GF通证销售期间购买到GF通证。请填写以下表格，并在GF通证销售选项中选择您想要购买的GF通证的数量。',
    buy_tips_text2 : '有确切日期的确认电子邮件将很快发送到您-敬请期待！',
    buy_confirm_btn : '提交',
    buy_tips_text3 : '社区理事会邮箱：info@game.fund',
    email_item_title1 : '邮箱地址',
    email_item_title2 : '确认邮箱地址',
    fill_same_email : '你必须输入匹配的邮箱地址',
    fill_input_length : '不能输入超过50个字符',
    fill_empty_tip : '必填选项不能为空',
    read_satement_tip : '请先阅读声明条款并接受，再提交',
    must_fill : '*必填',
    email_notice : '重要：确保能够联系到您的邮箱地址，可选择修改',
    telegram_name : 'Telegram用户名',
    sale_count_title : '请填写您计划求购数量（单位：ETH）',
    btc_address : '您的BTC地址',
    eth_address : '您的ETH地址(ETH购买地址)',
    neo_address : '您的NEO地址(用于接收GF的地址，可在NEO官网申请)',
    read_accept : '阅读并接受',
    statementList : '声明条款',

    statement : '声明',
    statement_p1 : '任何美国，加拿大，中国及新加坡公民，永久居民或注册机构均不得购买GF通证; GF通证不得出售给任何美国，加拿大，中国和新加坡公民，永久居民或机构。',
    statement_p2 : 'GF通证不代表真实世界中的任何资产或权利（例如红股，公司股份或公司投票权）。',
    statement_p3 : 'GAME.FUND的具体计划可在官方通证销售之前进行调整。',
    statement_p4 : '参与GAME.FUND GF通证销售的参与者应充分阅读本网站上的内容，GAME.FUND白皮书和其他相关材料，作出审慎考虑并了解风险。',
    statement_p5 : '本网站，路线图和白皮书仅供参考，不得在任何情况下，以暗示或其他方式解释为出售或招揽购买，出售或交易任何商品，证券或货币。信息来自被认为是可靠的来源，但对未来的预测是不能保证的。',
    accept_btn : '接受',
    return_btn : '返回',

    whitelist_successful_title : 'GF通证认购白名单',
    whitelist_p1 : '您提交的求购意向信息已被记录',
    whitelist_p2 : '提示：有时邮件不能按时发送或被电子邮件客户端阻止为垃圾邮件，为了确保您不错过，请关注我们所有telegram上的最新消息。',
    whitelist_p3 : '在发送任何电子邮件之前，我们将在我们的官方telegram上发布最新消息。',
    whitelist_p4 : 'Facebook的地址',
    whitelist_p5 : 'Telegram的公告地址',
    whitelist_p6 : 'Telegram的聊天群地址',
    whitelist_p7 : '邮箱地址',
    whitelist_p8 : 'GitHub地址',
    whitelist_successful_confirm1 : '另写一份',

    check_code_error : '验证码错误',
    check_code : '验证码',
    change_code : '换一张',

    //服务条款页面内容
    server_page_title : '服务条款',
    server_page_p1 : '欢迎来到 GAME.FUND！',
    server_page_p2 : '感谢您使用我们的产品和服务（下称“服务”）。服务由GAMEFUND PTE.LTD.提供。',
    server_page_p3 : '您使用我们的服务即表示您已同意本条款。请仔细阅读。',
    server_page_p4 : '我们的服务范围非常广泛，因此有时还会适用一些附加条款或产品要求（包括年龄要求）。附加条款将会与相关服务一同提供，并且在您使用这些服务后，成为您与我们所达成的协议的一部分。',
    server_page_p5 : '使用服务',
    server_page_p6 : '您必须遵守服务中提供的所有政策。',
    server_page_p7 : '请勿滥用我们的服务。举例而言，请勿干扰我们的服务或尝试使用除我们提供的界面和指示以外的方法访问这些服务。您仅能在法律（包括适用的出口和再出口管制法律和法规）允许的范围内使用我们的服务。如果您不遵守我们的条款或政策，或者我们在调查可疑的不当行为，我们可以暂停或停止向您提供服务。',
    server_page_p8 : '使用我们的服务并不让您拥有我们的服务或您所访问的内容的任何知识产权。除非您获得相关内容所有者的许可或通过其他方式获得法律的许可，否则您不得使用服务中的任何内容。本条款并未授予您使用我们服务中所用的任何商标或标志的权利。请勿删除、隐藏或更改我们服务上显示的或随服务一同显示的任何法律声明。',
    server_page_p9 : '我们的服务会显示一些不属于GAME.FUND的内容。这些内容由发布的实体承担全部责任。我们可能会审查相关内容，以确定其是否违法或违反了我们的政策；如果我们有理由相信该内容违反了我们的政策或违法，我们可以将其删除或拒绝显示。不过，这并不意味我们必然会审查内容，因此请勿想当然地认为我们在进行审查。',
    server_page_p10 : '在您使用服务的过程中，我们可能会向您发送服务公告、管理消息和其他信息。您可以选择不接收上述某些信息。',
    server_page_p11 : '我们的部分服务可在移动设备上使用。在使用此类服务时，请勿因此而分散注意力和违反交通或安全法。',
    server_page_p12 : 'GAME.FUND帐户',
    server_page_p13 : '为了使用我们的某些服务，您可能需要一个GAME.FUND帐户。您可以创建自己的GAME.FUND帐户。如果您使用的是由第三方分配的GAME.FUND帐户，可能需要遵守另外的条款或附加条款，并且您的管理员可能有权访问或停用您的帐户。',
    server_page_p14 : '为保护您的GAME.FUND帐户，请务必保管好您的密码并对外保密。您应对自己GAME.FUND帐户上发生的活动或通过该帐户进行的活动负责。尽量不要在其他应用中使用与GAME.FUND帐户相同的密码。如果您发现有人在未经授权的情况下使用了您的密码或GAME.FUND帐户，请立即更换您的账户密码。',
    server_page_p15 : '隐私与版权保护',
    server_page_p16 : 'GAME.FUND的隐私权政策介绍了您在使用我们的服务时，我们会如何处理您的个人数据和保护您的隐私。使用我们的服务即表示您同意GAME.FUND可以按照我们的隐私权政策使用您的个人数据。',
    server_page_p17 : '我们会根据相关法律规定的流程，对涉嫌侵犯版权的通知作出回应并终止屡次侵权人的帐户。',
    server_page_p18 : '我们会向版权持有人提供信息，以帮助他们在线管理自己的知识产权。如果您认为有人侵犯了您的版权并希望通知我们，可以联系我们e-mail：info@game.fund获取帮助。',
    server_page_p19 : '您在我们服务中发布的内容',
    server_page_p20 : '我们的某些服务允许您上传、提交、存储、发送或接收内容。您保留对该内容持有的任何知识产权的所有权。简言之，属于您的内容依然归您所有。',
    server_page_p21 : '当您将内容上传、提交、存储或发送到我们的服务，以及通过我们的服务上传、提交、存储、发送或接收内容时，您授予GAME.FUND一项全球性的许可，允许GAMEFUND PTE.LTD.使用、托管、存储、复制、修改、创建衍生作品（例如，我们为了使您的内容更好地与我们的服务配合使用而进行翻译、改编或其他更改，由此产生的作品）、传播、出版、公开演示、公开展示和分发此类内容。您在此许可中授予的权限，仅能用于运营、宣传和改进我们的服务，以及开发新的服务。该项许可在您停止使用我们的服务后依然有效。某些服务可能会向您提供一些方法，用于访问和删除您提供给该服务的内容。此外，我们某些服务中的条款或设置还会收窄我们对提交至相关服务的内容的使用范围。对于您提交至我们服务的任何内容，请确保您拥有向我们授予此许可的必要权利。',
    server_page_p22 : '我们的自动化系统会对您的内容（包括电子邮件）进行分析，以便为您提供更符合个人需求的产品功能，例如自定义搜索结果、量身定制的广告等。当您发送、接收以及存储内容时，我们的系统就会进行这项分析。',
    server_page_p23 : '如果您已拥有GAME.FUND帐户，我们可能会在我们的服务（包括广告以及其他商业环境）中，显示您的个人资料姓名、个人资料照片以及您在GAME.FUND上或与GAME.FUND帐户相关联的第三方应用上执行的操作（例如，+1以及您发表的评价和评论）。',
    server_page_p24 : '关于我们服务中的软件',
    server_page_p25 : '如果某项服务要求下载或包含可下载软件，该软件可能会在新版本或新功能推出时，在您的设备上自动更新。某些服务可能会允许您自行调整自动更新设置。',
    server_page_p26 : 'GAMEFUND PTE.LTD.授予您免许可使用费的、不可转让的、非独占的全球性个人许可，允许您使用由GAME.FUND提供的、包含在服务中的软件。本许可仅旨在让您通过本条款允许的方式使用由GAME.FUND提供的服务并从中受益。您不得复制、修改、发布、出售或出租我们的服务或所含软件的任何部分，也不得进行反向工程或试图提取该软件的源代码，除非法律禁止上述限制或您已获得GAME.FUND的书面许可。',
    server_page_p27 : '开源软件对我们很重要。我们的服务中所使用的部分软件可能是根据开放源代码许可提供的，我们将会向您提供该许可。开放源代码许可中的规定可能会明确推翻上述某些条款。',
    server_page_p28 : '修改和终止服务',
    server_page_p29 : '我们始终在不断更改和改进我们的服务。我们可能会增加或删除功能，也可能暂停或彻底停止某项服务。',
    server_page_p30 : '您可以随时停止使用我们的服务，尽管我们对此表示非常遗憾。GAME.FUND也可能随时停止向您提供服务，或随时对我们的服务增加或设置新的限制。',
    server_page_p31 : '我们认为您拥有自己数据的所有权并保留对此类数据的访问权限，这一点非常重要。如果我们停止某项服务，在合理可能的情况下，我们会向用户发出合理的提前通知，并让用户有机会将信息从服务中汇出，但对于第三方产生的数据变动与丢失（例如：游戏停服等），不包含在GAME.FUND的服务中。',
    server_page_p32 : '保证和免责声明',
    server_page_p33 : '我们在提供服务时将会尽到商业上合理水平的技能和注意义务，希望您会喜欢使用它们。但有些关于服务的事项恕我们无法作出承诺。',
    server_page_p34 : '除本条款或附加条款中明确规定的内容外，GAMEFUND PTE.LTD.及其供应商和分销商对服务均不作任何具体承诺。例如，我们对服务内容、服务的具体功能，或其可靠性、可用性或满足您需要的能力不作任何承诺。服务是“按原样”提供的。',
    server_page_p35 : '某些司法管辖区域会规定特定保证，例如适销性、特定目的适用性及不侵权的默示保证。在法律允许的范围内，我们排除所有保证。',
    server_page_p36 : '服务的责任',
    server_page_p37 : '在法律允许的范围内，GAMEFUND PTE.LTD.及其供应商和分销商不承担利润损失、收入损失或数据、财务损失或间接、特殊、后果性、惩戒性或惩罚性损害赔偿的责任。',
    server_page_p38 : '在所有情况下，GAMEFUND PTE.LTD.及其供应商和分销商对于任何不能合理预见的损失或损害不承担责任。',
    server_page_p39 : '我们理解在一些国家/地区，您作为消费者可以享有某些法定权利。如果您出于个人目的而使用服务，对于任何不能通过合同放弃的消费者法定权利，本条款或附加条款不作限制。',
    server_page_p40 : '服务的商业使用',
    server_page_p41 : '如果您代表某家企业使用我们的服务，该企业必须接受本条款。对于因使用本服务或违反本条款而导致的或与之相关的任何索赔、起诉或诉讼，包括因索赔、损失、损害赔偿、起诉、判决、诉讼费和律师费而产生的任何责任或费用，该企业应对GAMEFUND PTE.LTD.及其关联机构、管理人员、代理机构和员工进行赔偿并使之免受损害。',
    server_page_p42 : '关于本条款',
    server_page_p43 : '我们可以修改上述条款或任何适用于某项服务的附加条款，例如，为反映法律的变更或我们服务的变化而进行的修改。您应当定期查阅本条款。我们会在本网页上公布这些条款的修改通知。我们会在适用的服务中公布附加条款的修改通知。所有修改的适用具有追溯力，除非我们发出公告废止该条款。同时，对服务新功能的特别修改或由于法律原因所作的修改将立即生效。如果您不同意服务的修改条款，应停止使用服务。',
    server_page_p44 : '本条款约束GAMEFUND PTE.LTD.与您之间的关系，且不创设任何第三方受益权。',
    server_page_p45 : '如果您不遵守本条款，且我们未立即采取行动，并不意味我们放弃我们可能享有的任何权利（例如，在将来采取行动）。',
    server_page_p46 : '如果某一条款不能被强制执行，这不会影响其他条款的效力。',

    //邀请函
    invitation_page_title1 : '基于区块链的全球去中心化游戏民有',
    invitation_page_title2 : '民治民享公共社区诚邀您加入',
    invitation_page_code : '邀请码',
    invitation_page_codetip : '在获取资格页面输入邀请码，可获得参与GAME.FUND社区的资格',
    press_code_tip : '长按识别二维码了解详情',
    down_two_span : '如已有账号请',

    reset_title_text: '密码重置',
    reset_ltitle_text1: '新密码',
    reset_ltitle_text2: '确认密码',
    reset_btn: '提交',
    resetpwd_success: '密码重置成功！',
    resetpwd_fail: '密码重置失败，请重试！',

    //新变动2.10
    code_date : '注意：有效期三天，一次有效',
    atop_half_text1 : '根据本社区推广奖励政策，鼓励邀请您朋友来参与，您可从“45%内容激励GF池”中获得您朋友实际投资5%的等值GF。',
    //2.11
    r_country : '居住国家或地区',
    whitelist_successful_confirm3 : '您可从“45%内容激励GF池”中获得您朋友实际投资5%的等值GF',
    whitelist_successful_confirm2 : '邀请好友',
}

//-----------------------------------------英文版
var en = {
     //index.html
    item_title2 : 'Development tools released',
    item_title3 : 'Based on block chain transparent autonomy of the game ecological one station closed loop',
    item_title4 : '“Share” the shared public community',
    item_btn1 : 'White paper',
    item_btn2 : 'Source code',
    c2_index_h2 : 'Case show',
    c2_index_title : 'BCreator Development Tool Released',
    c2_index_title1 : 'The first phase of sales BCreator license, using the recommender system,' +
    'buyers need to activate purchase qualification by invitation code.',
    //c2_index_title2 : 'buyers need to activate purchase qualification by invitation code.',
    c2_index_content0 : '3D HTML5 cloud engine created by China',
    c2_index_content1 : 'Developers can create 3D/VR/AR/MR with BCreator and apply it to games, military, tourism, e-commerce, education, etc.',
    c2_index_content2 : 'Dynasty Warriors',
    c2_index_content3 : 'The first full-view, movie-level action effects 3D H5 game',
    c2_index_content4 : 'Full Memory',
    c2_index_content5 : 'This is a 3D game of won the ChinaJoy Jinling award and the top ten award of the publication administration',
    c2_index_content6 : 'Military VR',
    c2_index_content7 : 'Nation Agency designated 3D/VR engine',
    language_version : 'English',
    
    //login.html
    ltitle_text1 : 'E-mail',
    ltitle_text2 : 'Password',
    login_btn : 'Log in',
    forget_password : 'Forgot password',
    register_account : 'Register',
    //registered.html
    rtitle_text1 : 'E-mail',
    rtitle_text2 : 'Password',
    rtitle_text3 : 'Confirm password',
    rtitle_text4 : 'Invitation code',
    rtitle_text5 : 'Details',
    register_btn : 'Register',
    rto_login : 'Log in',
    find_detail : 'View details',
    invite_password_text: 'Involvement in the GAME.FUND community requires verification by the invitation code, please see the invitation code description',
    //forget_psw.html
    ftitle_text : 'E-mail',
    email_btn : 'Send',
    fto_login : 'Log in',
    forget_password_text: 'Please fill in the e-mail address you used when registering,you will receive an email alert on how to reset your password.',
    //get_qualified.html
    
    gtop_half_text2 : 'get the purchase registration eligibility, eligible users can use the',
    gtop_half_text3 : 'Kiss points to buy invitation code and give it to friends.',
    gbottom_input_title : 'Please enter your invitation code to activate your identity',
    gbottom_input : 'Please enter your invitation code',
    gconfirm_activation : 'Confirm activation',
    gsuccessful_title : 'Activation successful',
    gsuccessfull_text1 : 'Congratulations, you have been granted BCreator license registration quota for',
    gsuccessfull_text2 : 'purchasing development tools',
    gactivation_successful_confirm : 'Confirm',
    //already_get_qualified.html
    abottom_input_title : 'Please enter the name of the person you are invited to',
    invited_name_input : 'Please enter the name of inviter',
    aconfirm_activation : 'Generate invitation code',
    share_tips : 'Share tips：long press pictures to save or share',
    //buy.html
    currency_item_title : 'Please select payment currency',
    wallet_item_title : 'Please enter the payment account of the payment currency selected in the previous step',
    num_item_title : 'Please enter the mumber of purchased BCreator license',
    need_pay_num : 'Need to pay',
    bsuccessful_title : 'Registration successful!',
    bsuccessfull_text : 'Please enter my order for details',
    bactivation_successful_confirm : 'Confirm',
    //my_order.html
    order_title : 'My order',
    //my_invitation.html
    invitation_title : 'Invite statistics',
    statistics_title1 : 'Total',
    statistics_title2 : 'Used',
    statistics_title3 : 'Expired',
    show_available : 'Usable',
    show_used : 'Used',
    //my_income.html
    income_title : 'My income',
    //head.js
    download_app : 'APP download',
    my_order : 'My order',
    my_invitation : 'Invite statistics',
    my_income : 'My income',
    loginout : 'Logout',
    //foot.js
    index_btn : 'Project introduction',
    getQualified : 'Get qualified',
    please_gqualified : 'Please obtain the qualification first!',
    //index.js
    please_downloadapp : 'Please click on APP to download and play the game！',
    //already_get_qualified.js
    generate_fail : 'Generate failed!',
    operate_error : 'The operation is abnormal, please try again！',
    not_fill_name : 'The name of the inviter did not fill in',
    fill_text1 : 'Based on block chain transparent autonomy of the game ecological one station closed loop',
    fill_text2 : '“Share” the shared public community',
    fill_text3 : 'Enter the invitation code on the qualification page to apply for registration of the purchased software',
    //buy.js
    infor_fill : 'Fill in the data error or incomplete!',
    fill_right_email : 'Please input the correct email address',
    //forget_psw.js
    send_success : 'Send successfully, please login email to change password',
    send_fail : 'Failed to send',
    //get_qualified.js
    fill_code : 'Please enter the invitation code',
    un_code : 'Invalid invitation code!',
    code_used : 'Invitation code has been used!',
    expried_code : 'Invitation code has expired!',
    user_invited : 'User has been invited, can not be repeated binding!',
    //login.js
    login_error : 'Account does not exist or the password is wrong!',
    //my_income.js
    no_more_sum : 'No more data',
    //my_invitation.js
    will_to : 'After ',
    expried : 'expired',
    //my_order.js
    waite_ex : 'Wait for payment',
    under_review : 'Pending',
    deal_success : 'Trading success',
    o_expreid : 'Expired',
    status_exception : 'Abnormal status',
    buy_sum : 'Quantity',
    need_pay : 'Need to pay',
    tradeno : 'Order number：',
    find_detail : 'View details',
    pay_info : 'Payment information：',
    collect_money : 'Receiving wallet account',
    trade_info : 'Order information：',
    product_name : 'Product name：',
    product_num : 'Quantity：',
    need_pay_money : 'Need to pay：',
    pay_num : 'Payment wallet account：',
    trade_time : 'Order generation time：',
    trade_status : 'Order status：',
    //register.js
    inspect : 'Please check the information is correct before submitting!',
    number_error : 'Account does not exist or the password is wrong!',
    number_exist : 'Account already exists!',
    redister_fail : 'Registration failed!',
    system_req : 'At least 7 characters, including numbers and letters, no spaces',
    fill_pwd : 'You must enter the correct password',
    //新变动1
    buy_btn : 'Pre-registration',
    gtop_half_title : 'Why do I need an invitation code?',
    gtop_half_text1 : 'Participation in GAME.FUND community quota using referral system, participants need to activate their status through the invitation code, access to qualifications.',
    gbottom_half_title : 'How to get invitation code?',
    gbottom_half_text_ul_p1 : 'Ask an eligible user for an invitation code to gain eligibility.',
    gbottom_half_text_ul_p2 : 'Please contact GAME.FUND Community Council, e-mail：info@game.fund',
    already_registration : 'You have pre-registered',
    atop_half_title1 : 'Help others get involved in the',
    atop_half_title2 : 'community',
    // atop_half_text1 : 'Participation in the GAME.FUND community is based on a referral system',
    atop_half_text2 : ' and is validated by community invitation code.',
    abottom_half_title1 : 'Invite friends to join ',
    abottom_half_title2 : 'G',
    abottom_half_title3 : 'AME.',
    abottom_half_title4 : 'F',
    abottom_half_title5 : 'UND',
    // buy_tips : 'Registration tips',
    // buy_tips_text1 : 'Interested in participating in the GAME.FUND community of users,',
    // buy_tips_text2 : 'Please click the pre-registration button',
    // buy_confirm_btn : 'Pre-registration',
    // buy_tips_text3 : 'Community Council e-mail：info@game.fund',
    rtitle_text4 : 'Invitation code',

    //新变动2
    account_login : 'Login',
    account_register : 'Register',
    password_find : 'Forgot Password',
    joinWhitelist : 'Join whitelist',
    pleaseReadStmt : 'Please read the agreement first and accept it, then register',
    fill_email_length : 'The mailbox address can not exceed 50 characters',
    password_length : 'The password length can not more than 50 characters',
    readAccept : 'Read and accept',
    serverList : 'Terms of service',
    getInvitationBtn : 'Generate invitation code',
    registerSuccess : 'Account registration success!',
    joinGAME : 'Whether to join the GAME.FUND whitelist?',
    continueBtn : 'Join', 
    // atop_half_text1 : 'Participation in the GAME.FUND community is based on a referral system, register a community account need to be verified by community invitation code. The recommender will get 5% of the total amount of GF token purchased by the recommended person.',
    atop_half_text2 : 'register a community account need to be verified by community invitation code. ',
    atop_half_text3 : 'The recommender will get5% of the total amount of GF token purchased by the recommended person.',
    my_reward : 'My reward',
    buy_tip_title1_1 : 'Join the',
    buy_tip_title1_2 : 'whitelist',
    importent_tip : 'Important hints',
    buy_top_text1 : 'Once the whitelist reaches the maximum number, the channel of join whitelist will be closed. We will notify you through the official telegram notice group and mail.',

    buy_tips_1 : 'GAME.FUND',
    buy_tips_2 : 'GF token subscription whitelist',
    buy_tips_text1 : 'We are creating a whitelist for our community. You have been with us from the first day, and we want to make sure that you can purchase a GF token during our GF token sales. Please fill in the form below and select the number of GF token that you want to purchase.',
    buy_tips_text2 : 'The confirmation email with the exact date will be sent to you soon - please look forward to it!',
    buy_confirm_btn : 'Submit',
    buy_tips_text3 : 'Mailbox of Community Council：info@game.fund',
    email_item_title1 : 'E-mail address',
    email_item_title2 : 'Confirm Email Address',
    fill_same_email : 'You have to enter a matching mailbox address',
    fill_input_length : 'Cannot enter more than 50 characters',
    fill_empty_tip : 'Required options cannot be empty',
    read_satement_tip : 'Please read the terms of the declaration first and accept it, then submit it',
    must_fill : '*Required',
    email_notice : 'Important: make sure that we can contact your with the mailbox address, and you can choose to modify it',
    telegram_name : 'Telegram User name',
    sale_count_title : 'Please fill in your plan to buy quantity (unit: ETH)',
    btc_address : 'Your BTC address',
    eth_address : 'Your ETH address (ETH out of the address)',
    neo_address : 'Your NEO address(Used to receive the address of GF, NEO official website can apply)',
    read_accept : 'Read and accept',
    statementList : 'Statement',
    check_code_error : 'Verification code error',
    check_code : 'Verification code',
    change_code : 'Change',

    //声明条款
    statement : 'Statement',
    statement_p1 : 'American, Canadian, Chinese and Singaporean citizens, permanent residents or registered institutions are not allowed to purchase GF token. GF token shall not be sold to any American, Canadian, Chinese and Singaporean citizens, permanent residents or institutions.',
    statement_p2 : 'GF token does not represent any assets or rights in the real world (such as bonus shares, share in a company or the right to vote).',
    statement_p3 : 'The specific plan of GAME.FUND can be adjusted before the sale of the official token.',
    statement_p4 : 'Participants who participated in GAME.FUND GF token sales should fully read the content on this website, GAME.FUND white paper and other related materials, making careful consideration and understanding of risks.',
    statement_p5 : 'The website, road map and white paper are for reference only. In any case, it can not be interpreted as an implied or other means to sell or recruit, sell or trade any commodity, securities or currency. Information comes from being regarded as a reliable source, but it is not guaranteed for future predictions.',
    accept_btn : 'accept',
    return_btn : 'Return',

    ////加入whiteList成功页面
    whitelist_successful_title : 'GF token subscription whitelist',
    whitelist_p1 : 'The purchase intent information you submitted has been recorded',
    whitelist_p2 : "Hint: sometimes mail can't be sent on time or is blocked by e-mail client as junk mail. In order to make sure you don't miss any message, please pay attention to the latest news on all of our telegram.",
    whitelist_p3 : 'Before sending any email, we will release the news on our official telegram.',
    whitelist_p4 : "Facebook address",
    whitelist_p5 : "Telegram's notice address",
    whitelist_p6 : "Telegram's chat group address",
    whitelist_p7 : 'E-mail address',
    whitelist_p8 : 'GitHub address',
    whitelist_successful_confirm1 : 'Write another',

    //服务条款页面内容
    server_page_title : 'Terms of Service',
    server_page_p1 : 'Welcome to GAME.FUND！',
    server_page_p2 : 'Thank you for using our products and services (hereinafter referred to as "service"). Service is provided by GAMEFUND PTE.LTD.',
    server_page_p3 : 'By using our services, you agree to the Terms. Please read carefully.',
    server_page_p4 : 'We have a very wide range of services, so sometimes additional terms or product requirements (including age requirements) apply. Additional terms and conditions will be provided with the Services and will become part of Your agreement with us after you use them.',
    server_page_p5 : 'Use of services',
    server_page_p6 : 'You must comply with all the policies provided in the service.',
    server_page_p7 : 'Please do not abuse our service. For example, do not interfere with our services or try to access these services in a way other than the interfaces and instructions we provide. You can only use our services within the scope of the law (including applicable export and re export control laws and regulations). If you do not comply with our terms or policies, or we are investigating suspicious misconduct, we can suspend or stop providing services to you.',
    server_page_p8 : 'Using our service does not allow you to have any intellectual property rights of our service or the content you are accessing. You are not allowed to use any content of the service unless you get permission from the owner of the content or obtain permission from the law in other ways. This clause does not grant you the right to use any trademark or sign used in our service. Do not delete, hide or change any legal statements displayed on our service or displayed with the service.',
    server_page_p9 : 'Our service will show some contents that do not belong to GAME.FUND. These contents are all responsible for the released entities. We may examine related contents to determine whether it is illegal or contrary to our policy; if we have reason to believe that the content violates our policy or illegal, we can delete it or refuse to show it. However, this does not mean that we are bound to review the content, so do not take it for granted that we are conducting a review.',
    server_page_p10 : 'In the course of your service, we may send you service bulletins, management messages, and other information. You can choose not to receive some of the above information.',
    server_page_p11 : 'Some of our services can be used on mobile devices. In the use of such services, do not distract attention and violate traffic or safety laws.',
    server_page_p12 : 'GAME.FUND account',
    server_page_p13 : 'In order to use some of our services, you may need a GAME.FUND account. You can create your own GAME.FUND account. If you use the GAME.FUND account allocated by the third party, you may need to comply with other terms or additional terms, and your administrator may have the right to access or disable your account.',
    server_page_p14 : 'In order to protect your GAME.FUND account, be sure to keep your password and keep it confidential. You are responsible for the activities that occur on your GAME.FUND account or the activities carried out through the account. Try not to use the same password as the GAME.FUND account in other applications. If you find that someone has used your password or GAME.FUND account without authorization, please replace your account password immediately.',
    server_page_p15 : 'Privacy and copyright protection',
    server_page_p16 : 'The privacy policy of GAME.FUND introduces how you handle your personal data and protect your privacy when you use our services. Using our service means that you agree that GAME.FUND can use your personal data in accordance with our privacy policy.',
    server_page_p17 : "We will respond to notifications suspected of infringement of copyright and terminate repeated infringers' accounts in accordance with the procedures stipulated in the relevant laws.",
    server_page_p18 : 'We will provide information to the copyright holders to help them manage their intellectual property online. If you think someone has infringed your copyright and would like to inform us, you can contact us with e-mail:info@game.fund for help.',
    server_page_p19 : 'What you have published in our service',
    server_page_p20 : 'Some of our services allow you to upload, submit, store, send, or receive content. You retain ownership of any intellectual property held in this content. In short, the content that belongs to you still belongs to you.',
    server_page_p21 : 'When you upload content, submit, stored or transmitted to our services, and through our services to upload, submission, storage, sending or receiving content, you grant GAME.FUND a worldwide license, allowing GAMEFUND PTE.LTD. hosting, storage, use, copy, modify, create derivative works (for example, in order to make our you better with the content of our service with the use of translation, adaptation or other changes, the resulting works), communication, publishing, public presentation, public display and dissemination of such content. The permissions you have granted in this license can only be used to operate, propagate and improve our services, as well as to develop new services. The license is still valid after you stop using our service. Some services may provide you with some ways to access and delete what you provide to the service. In addition, the terms and settings in some of our services also narrow the scope of our use of the content submitted to the related services. Please make sure that you have the necessary right to grant us this License for any content you submit to our service.',
    server_page_p22 : 'Our automation system will analyze your content (including e-mail) to provide you with more personal functions, such as custom search results, customized advertisements, etc. When you send, receive, and store the content, our system will do this analysis.',
    server_page_p23 : 'If you have a GAME.FUND account, we may in our services (including advertising and other commercial environment), displays the name of your personal information, personal information and photos from your GAME.FUND or GAME.FUND account and related to the implementation of the third party application with the operation (e.g., +1 and evaluation of your published and review).',
    server_page_p24 : 'About the software in our service',
    server_page_p25 : 'If a service is required to download or contain downloadable software, the software may be automatically updated on your device when the new version or new feature is introduced. Some services may allow you to adjust the automatic update settings.',
    server_page_p26 : 'GAMEFUND PTE.LTD. grants you a royalty free, non transferable and exclusive exclusive personal license, which allows you to use the software that is provided by GAME.FUND and included in the service. This license is only intended to allow you to use and benefit from the services provided by GAME.FUND through the terms of this clause. You shall not copy, modify, publish, sell or rent any part of our services or software, nor reverse engineer or attempt to extract the source code of the software unless the law prohibits the above restrictions or you have obtained the written permission of GAME.FUND.',
    server_page_p27 : 'Open source software is very important to us. Some of the software used in our service may be provided according to the open source license, and we will provide you with the license. The provisions in the open source license may clearly overthrow some of the above clauses.',
    server_page_p28 : 'Modify and terminate service',
    server_page_p29 : 'We are constantly changing and improving our service. We may add or delete functions, or suspend or completely stop a service.',
    server_page_p30 : 'You can stop using our service at any time, although we are very sorry to say that. GAME.FUND may also stop providing services to you at any time, or at any time to add or set new restrictions on our services.',
    server_page_p31 : "We think it's very important that you have ownership of your own data and retain access to such data. If we stop a service, in a reasonably possible, we will give reasonable notice to the user, and allows users to have the opportunity to export information from the service, but for the change and loss of third party data generated (for example: the game to stop taking, etc.) are not included in the service of GAME.FUND.",
    server_page_p32 : 'Declaration of assurance and Disclaimer',
    server_page_p33 : "We will do our best to provide a reasonable level of business skills and duty of care when we provide services, and I hope you will like to use them. But there are some things about the service that we can't make a commitment.",
    server_page_p34 : 'GAMEFUND PTE.LTD. and its suppliers and distributors do not make any specific commitments to the service, except for the contents specified in this clause or additional clause. For example, we do not make any commitment to the content of the service, the specific functions of the service, or its reliability, availability, or the ability to meet your needs. The service is provided "as it is".',
    server_page_p35 : 'Certain jurisdictions provide specific guarantees, such as marketability, specific purpose applicability, and implied warranties of non infringement. We exclude all guarantees within the scope of the law.',
    server_page_p36 : 'Responsibility of service',
    server_page_p37 : 'Within the scope permitted by law, GAMEFUND PTE.LTD. and its suppliers and distributors are not liable for loss of profits, loss of revenues or data, financial loss or indirect, special, consequential, disciplinary or punitive damages.',
    server_page_p38 : 'In all cases, GAMEFUND PTE.LTD. and its suppliers and distributors are not responsible for any loss or damage that can not be reasonably foreseen.',
    server_page_p39 : 'We understand that in some countries / regions, you can enjoy certain legal rights as consumers. If you use the service for personal purposes, there is no restriction on any of the legal rights of the consumer that can not be waiver through the contract, this clause or the additional clause.',
    server_page_p40 : 'Commercial use of services',
    server_page_p41 : 'If you use our service on behalf of a certain enterprise, the enterprise must accept this clause. Due to the use of the service or violation of the terms caused by or related to any claim, action or litigation, including any liability or expenses arising from claims, losses, damages, prosecution and judgment, litigation costs and legal fees, the enterprise should GAMEFUND PTE.LTD. and its related mechanism, management, agency and employee compensation and make against damage.',
    server_page_p42 : 'About this clause',
    server_page_p43 : 'We can modify the above terms or any additional clauses applicable to a service, for example, in order to reflect changes in the law or changes in our services. You should consult this clause on a regular basis. We will announce the amendments to these terms on this web page. We will announce the amendments to the additional terms in the applicable service. The application of all the amendments is traceability unless we have issued an announcement to abolish the clause. At the same time, the special modification of the new service function or the amendment to the legal cause will take effect immediately. If you do not agree to the terms of the service, you should stop using the service.',
    server_page_p44 : 'This clause constrains the relationship between GAMEFUND PTE.LTD. and you, and does not create any third party beneficiaries.',
    server_page_p45 : 'If you fail to comply with this clause and we do not act immediately, it does not mean that we shall give up any rights that we may enjoy (for example, take action in the future).',
    server_page_p46 : 'If a clause cannot be enforced, it will not affect the effectiveness of the other terms.',

    //邀请函
    invitation_page_title1 : 'The community based on global ',
    invitation_page_title3 : 'decentralization blockchain that ',
    invitation_page_title2 : 'of the people, by the people, for ',
    invitation_page_title4 : 'the people invites you to join it',
    invitation_page_code : 'Invitation code',
    invitation_page_codetip : 'Enter the invition code on the page of get qualifications',
    invitation_page_codetip1 : 'to get the chance to participate the community',
    press_code_tip : 'Scanning invitation code',
    down_two_span : 'If you have an account please',

    reset_title_text: 'Password Reset',
    reset_ltitle_text1: 'New password',
    reset_ltitle_text2: 'Confirm password',
    reset_btn: 'Submit',
    resetpwd_success: 'Password reset success!',
    resetpwd_fail: 'Password reset failed, please try again!',

    //新变动 2-10
    code_date : 'Note: Valid for 3 days, and once',
    atop_half_text1: 'According to the promotion policy of our community, the communtity encourages you to invite your friends to join, you can get the equivalent GF of 5% actually invested by your friends from "45% Content Incentive GF Pool" be encouragement.',
    r_country : 'Country or region where you live',
    whitelist_successful_confirm3 : 'You can get the equivalent GF of 5% actually invested by your friends from "45% Content Incentive GF Pool" be encouragement',
    whitelist_successful_confirm2 : 'Invite friends',
}


//-----------------------------------------日文版
var ja = {
     //index.html
    item_title2 : '開発ツール発表',
    item_title3 : 'ブロックチェーンの透明な自律性のゲーム生態学的なワンストップ閉ループに基づいて',
    item_title4 : '公共共同体コミュニティを「共有」する',
    item_btn1 : 'ホワイトペーパー',
    item_btn2 : 'ソースコード',
    c2_index_h2 : 'ケースショー',
    c2_index_title : 'BCreator 開発ツール発表',
    c2_index_title1 : '最初BCreator licenseの販売は推薦人制度を採用します、' + '購入者は招待コードで購入資格を有効にする。',
    //c2_index_title2 : '購入者は招待コードで購入資格を有効にする。',
    c2_index_content0 : '中国製の3D HTML5クラウドエンジ',
    c2_index_content1 : '開発者はBCreatorを使用して3D/VR/AR/MRを作成し、ゲーム、軍事、観光、電子商取引、教育などの分野に適用することができます。',
    c2_index_content2 : '『真三国戦記』',
    c2_index_content3 : '最初のフルアングル、映画レベルのアクション効果の3D H5ゲーム',
    c2_index_content4 : '『全面メモリ』',
    c2_index_content5 : 'ChinaJoy金翎賞と出版部門トップテン賞を受賞したの3D次世代ゲーム',
    c2_index_content6 : '『軍事VR』',
    c2_index_content7 : '国の機関のよって指定された3D/VRエンジン',
    language_version : '日語',
    //login.html
    ltitle_text1 : 'メール',
    ltitle_text2 : 'パスワード',
    login_btn : 'ログイン',
    forget_password : 'パスワードを忘れた',
    register_account : '新規登録',
    //registered.html
    rtitle_text1 : 'メール',
    rtitle_text2 : 'パスワード',
    rtitle_text3 : 'パスワード確認',
    rtitle_text4 : '招待コード',
    rtitle_text5 : '詳細',
    register_btn : '新規登録',
    rto_login : 'ログイン',
    find_detail : '詳細を見る',
    invite_password_text: 'GAME.FUNDコミュニティに関与するには、招待コードによる確認が必要です。招待コードの説明をご覧ください',
    //forget_psw.html
    ftitle_text : 'メール',
    email_btn : '送信',
    fto_login : 'ログイン',
    //get_qualified.html
    gtop_half_text2 : 'が購入登記資格を取得できる、そして資格取得のユーザーも',
    gtop_half_text3 : 'Kissポイントを使用してコミュニティ招待コードを購入して友達に送ることができる。',
    gbottom_input_title : '身元を認証するの招待コードを入力してください',
    gbottom_input : '招待コードを入力してください',
    gconfirm_activation : '認証',
    gsuccessful_title : '認証成功',
    gsuccessfull_text1 : '開発ツール購入するのBCreator license登記クオータ',
    gsuccessfull_text2 : '獲得おめでとう',
    gactivation_successful_confirm : '確認',
    //already_get_qualified.html
    abottom_input_title : '招待したいの人の名前を入力してくだいさい',
    invited_name_input : '招待者の名前を入力してください',
    aconfirm_activation : '招待コード生成',
    share_tips : '共有ヒント：ピクチャを長押して保存また共有する',
    //buy.html
    currency_item_title : '支払い通貨を選択してください',
    wallet_item_title : '前のステップで選択した支払い通貨の支払い口座を入力してください',
    num_item_title : 'BCreator licenseの購入数量を入力してください',
    need_pay_num : '費用',
    bsuccessful_title : '登記成功！',
    bsuccessfull_text : '詳細は私の注文で調べてください。',
    bactivation_successful_confirm : '確認',
    //my_order.html
    order_title : '私の注文',
    //my_invitation.html
    invitation_title : '招待統計',
    statistics_title1 : '合計',
    statistics_title2 : '使用済',
    statistics_title3 : '期限切れ',
    show_available : '使用可能',
    show_used : '使用済',
    //my_income.html
    income_title : '私の収入',
    //head.js
    download_app : 'APPダウンロード',
    my_order : '私の注文',
    my_invitation : '招待統計',
    my_income : '私の収入',
    loginout : 'ログアウト',
    //foot.js
    index_btn : 'プロジェクトの紹介',
    getQualified : '資格獲得',
    please_gqualified : 'まず資格を取得してください!',
    //index.js
    please_downloadapp : 'APPをクリックしてゲームをダウンロードして、体験してくだいさい！',
    //already_get_qualified.js
    generate_fail : '生成失敗！',
    operate_error : '操作が異常です、もう一度お試してください！',
    not_fill_name : '招待者の名前を入力してください！',
    fill_text1 : 'ブロックチェーンの透明な自律性のゲーム生態学的なワンストップ閉ループに基づいて',
    fill_text2 : '公共共同体コミュニティを「共有」する',
    fill_text3 : '資格取得ページに招待コードを入力して、ソフトウェアを購入するの登記クオータを申請する',
    //buy.js
    infor_fill : 'データ入力エラーまたは不完全！',
    fill_right_email : '正しいメールアドレスを入力してください',
    //forget_psw.js
    send_success : '送信成功、メールログインしてパスワードを変更してください。',
    send_fail : '送信失敗',
    //get_qualified.js
    fill_code : '招待コードを入力してください',
    un_code : '招待コードが無効です！',
    code_used : '招待コードが使用されました！',
    expried_code : '招待コードが期限切れです！',
    user_invited : 'ユーザーは招待されました、多重バインドすることができません！',
    //login.js
    login_error : 'アカウントが存在しませんまたはパスワードエラー！',
    //my_income.js
    no_more_sum : 'これ以上の情報はありません',
    //my_invitation.js
    will_to : '有効期限が',
    expried : '切れます',
    //my_order.js
    waite_ex : 'お支払い待ち',
    under_review : 'レビュー中',
    deal_success : '取引成功',
    o_expreid : '期限切れ',
    status_exception : '状態異常',
    buy_sum : '購入数量：',
    need_pay : '費用',
    tradeno : '注文番号：',
    find_detail : '詳細',
    pay_info : '支払い情報：',
    collect_money : '現金受取ウォレットアカウント',
    trade_info : '注文情報：',
    product_name : '製品名',
    product_num : '製品数量：',
    need_pay_money : 'お支払い金額：',
    pay_num : 'お支払いウォレットアカウント：',
    trade_time : '注文生成時間：',
    trade_status : '注文状態：',
    //register.js
    inspect : '提出する前に情報が正しいことを確認してください！',
    number_error : 'アカウントが存在しませんまたはパスワードエラー！',
    number_exist : 'アカウントは既に存在します',
    redister_fail : '新規登録失敗！',
    system_req : '少なくとも7文字、数字と文字を含む、スペースなし',
    fill_pwd : '正しいパスワードを入力してください',
    //新变动1
    buy_btn : '事前登録',
    gtop_half_title : 'なぜ招待コードが必要なのですか？',
    gtop_half_text1 : '紹介システムを使用してGAME.FUNDコミュニティクォータに参加するには、参加者は招待コード、資格へのアクセス',
    gbottom_half_title : '招待コードを取得するには？',
    gbottom_half_text_ul_p1 : '資格のあるユーザーに資格を得るための招待コードを尋ねる',
    gbottom_half_text_ul_p2 : 'GAME.FUNDコミュニティカウンシル、電子メールに連絡してください：info@game.fund',
    already_registration : 'あなたはあらかじめ登録されています',
    atop_half_title1 : '他のユーザーが',
    atop_half_title2 : 'コミュニティに参加できるようにする',
    // atop_half_text1 : 'GAME.FUNDコミュニティへの参加は照会システムに基づいており、',
    atop_half_text2 : 'コミュニティの招待コードによって検証されます、',
    abottom_half_title1 : 'に参加する友達を招待する ',
    abottom_half_title2 : 'G',
    abottom_half_title3 : 'AME.',
    abottom_half_title4 : 'F',
    abottom_half_title5 : 'UND',
    // buy_tips : '登録のヒント',
    // buy_tips_text1 : 'ユーザーのGAME.FUNDコミュニティに参加することに関心をお持ちの方、',
    // buy_tips_text2 : '事前登録ボタンをクリックしてください',
    // buy_confirm_btn : '事前登録',
    // buy_tips_text3 : 'コミュニティ評議会のEメール：info@game.fund',
    rtitle_text4 : '招待コード',

    //新变动2.1
    account_login : 'ログイン',
    account_register : '登録',
    password_find : 'パスワードを取り戻す',
    joinWhitelist : 'ホワイトリストに加入する',
    pleaseReadStmt : 'まず契約を読んで受け入れた後、登録してください',
    fill_email_length : 'メールアドレスは50文字以内にしてください',
    password_length : 'パスーワドは50文字以内にしてください',
    readAccept : '読んで受け入れます',
    serverList : 'サービス条項',
    getInvitationBtn : '招待コードを生成する',
    registerSuccess : 'アカウント登録成功！',
    joinGAME : 'ホワイトリストに加入しますか？',
    continueBtn : '加入する', 
    // atop_half_text1 : 'GAME.FUNDコミュニティへの参加は推薦システムに基づいており、コミュニティ アカウントはコミュニティ招待状コードで確認済み後登録できます。推薦者は推薦された人購入のGF通証の5%を獲得できます。',
    atop_half_text2 : 'アカウントはコミュニティ招待状コードで確認済み後登録できます。推薦者は',
    atop_half_text3 : '推薦された人購入のGF通証の5%を獲得できます。',
    my_reward : '私の奨励',
    buy_tip_title1_1 : '加入',
    buy_tip_title1_2 : 'ホワイトリスト',
    importent_tip : '重要なヒント',
    buy_top_text1 : 'ホワイトリスト人数が上限になりました後、ホワイトリストに加入するのチャンネルが閉じられます。公式telegram公告グループとメールでお知らせいたします。',

    buy_tips_1 : 'GAME.FUND',
    buy_tips_2 : 'GF通証購入申し込むホワイトリスト',
    buy_tips_text1 : '今はコミュニティにホワイトリストを作成しています。あなたは最初の日以来私たちと一緒にいます。GF通証販売の期間、あなたガGF通証を購入できることを確保するために、以下の表に記入してください、そしてGF通証販売の選択肢の中で購入したいの数を選択してください。',
    buy_tips_text2 : '確実な時間があるの確認メールがすぐにお送りいたします-お楽しみにしてください！',
    buy_confirm_btn : '提出',
    buy_tips_text3 : 'コミュニティ理事会メール：info@game.fund',
    email_item_title1 : 'メールアドレス',
    email_item_title2 : 'メールアドレス確認',
    fill_same_email : '一致したメールアドレスを入力してください',
    fill_input_length : '50文字以内にしてください',
    fill_empty_tip : '必須オプションには空にすることはできません',
    read_satement_tip : '声明条約を読んで受け入れた後、提出してください',
    must_fill : '*必須',
    email_notice : '重要：連絡できるのメールアドレスを入力してください、変更できます',
    telegram_name : 'Telegramユーザー名',
    sale_count_title : '数量を購入する計画を記入してください（単位：ETH）',
    btc_address : 'あなたのBTCアドレス',
    eth_address : 'あなたのETHアドレス(ETH購買アドレス)',
    neo_address : 'あなたのNEOアドレス(GFのアドレスを受け取るために使用され、NEOの公式ウェブサイトが応募できます)',
    read_accept : '読んで受け入れる',
    statementList : '声明条項',
    check_code_error : '検証コードエラー',
    check_code : '検証コード',
    change_code : 'チェンジ',

    //声明条款
    statement : '声明',
    statement_p1 : 'アメリカ、カナダ、中国やシンガポール公民、永住者または登録機関はGF通証を購入してはならない。GF通証をアメリカ、カナダ、中国とシンガポールの公民、永住者または機関に売却してはならない。',
    statement_p2 : 'GF通証は真実の世界のいかなる資産と権利を代表しない（例えばボーナス株、会社株式と会社選挙権）。',
    statement_p3 : 'GAME.FUNDの具体的な計画は公式通証販売する前に調整できる。',
    statement_p4 : 'GAME.FUND GF通証販売に参加するの者は本サイトの内容、GAME.FUNDホワイトペーパーと他の関連材料を十分に読んで、慎重に考え、リスクを知るべく',
    statement_p5 : '本サイト、ロートマップは参照用です。いかなる場合においても、暗示と他の方式で販売と売却勧誘、いかなる商品、証券または通貨の購入、売買または貿易と解釈してはならない。情報は信頼できると考えられる情報源からのものですが、将来の予測は保証されません。',
    accept_btn : '受け入れる',
    return_btn : '戻る',

    //加入whiteList成功页面
    whitelist_successful_title : 'GF通証購入申し込むホワイトリスト',
    whitelist_p1 : 'ご提出の意向情報が記録されています',
    whitelist_p2 : 'ヒント：メールが時間通りに送信できないやメールクライアントにスバムをみらされた時もあります、ニュースを見逃されように、telegramのニュースに注意してください。',
    whitelist_p3 : 'メールを送信する前に、私たちは公式telegramでニュースを発表します。',
    whitelist_p4 : 'Facebookアドレス',
    whitelist_p5 : 'Telegramの公告アドレス',
    whitelist_p6 : 'Telegramのチャートグループアドレス',
    whitelist_p7 : 'メールアドレス',
    whitelist_p8 : 'GitHubアドレス',
    whitelist_successful_confirm1 : 'もう一つを書く',

    //服务条款页面内容
    server_page_title : '利用規約',
    server_page_p1 : 'ようこそGAME.FUNDへ！',
    server_page_p2 : '私たちの製品とサービスをご利用いただき、ありがとうございます。サービスを提供し、GAMEFUND PTE.LTD。',
    server_page_p3 : 'あなたは私たちのサービスを使用して、この条項に同意しました。よく読んでください。',
    server_page_p4 : '私たちのサービスの範囲は非常に広くて、そのため、いくつかの付加条項や製品の要求（年齢を含む）を適用することができます。追加条項は関連サービスとともに提供し、これらのサービスを使用した後に、我々が達成した協議の一部となります。',
    server_page_p5 : '使用サービス',
    server_page_p6 : 'あなたはサービスに提供されたすべての政策を遵守しなければならない。',
    server_page_p7 : '私たちのサービスを悪用しないでください。例えば、私たちのサービスを妨害したり、私たちが提供したインタフェースと指示以外の方法でこれらのサービスを訪問することを試みないでください。法律（適用された輸出及び再輸出法及び法規）が許可された範囲内で私たちのサービスを使用することができます。もしあなたが私たちの条項や政策を遵守しないならば、あるいは私たちは不審な行為を調査している場合、私たちは一時停止または停止してあなたにサービスを提供することができます。',
    server_page_p8 : '私たちのサービスを使用して、あなたが私たちのサービスまたはあなたの訪問した内容のいかなる知的財産を持っていないようにしていません。関連内容の所有者の許可を得たり、その他の方法で法律の許可を得ない限り、サービス中のいかなる内容を使用してはならない。本条項は私たちのサービスにおいて使用されたいかなる商標または標識の権利を使用していない。私たちのサービスに表示されている、またはサービスとともに表示されるいかなる法律声明を削除するか、削除しないでください。',
    server_page_p9 : '私たちのサービスの表示に属していないかGAME.FUNDの内容。これらの内容は、発表された実体によってすべての責任を負う。我々は審査に関する内容を決定するかどうか、その違法や違反した我々の政策；もし我々が信じる理由はその内容の我々の政策や違法違反、あるいは拒絶表示は削除する。しかし、これは私たちが必ず内容を審査することを意味するからではなく、私たちが審査を進めているとは限らないと思わないでください。',
    server_page_p10 : 'あなたのサービスを使用する中で、私たちはあなたにサービスの掲示板、管理メッセージ、その他の情報を送信する可能性があります。上記のいくつかの情報を受信しないようにすることができます。',
    server_page_p11 : '我々の一部のサービスは、モバイル機器の上で使用することができます。このようなサービスを使用するときは、そのために注意して、交通や安全法に違反しないようにしてください。',
    server_page_p12 : 'GAME.FUNDアカウント',
    server_page_p13 : '私たちのいくつかのサービスを使用するため、あなたのGAME.FUNDアカウントが必要かもしれない。自分のGAME.FUNDアカウントを作成できます。を使用している場合は、第三者割り当てのGAME.FUNDアカウントを遵守する必要があります別のアイテムや付加条項、そしてあなたの管理人が権訪問や停止アカウント。',
    server_page_p14 : 'あなたのGAME.FUNDアカウントを守るために、ぜひ保管良いあなたのパスワードを対外秘密。あなたは自分の口座に対応GAME.FUND発生の活動や、アカウントの活動担当。なるべく他のアプリケーションで使用GAME.FUNDと同じアカウントのパスワード。あなたが認可されていない場合に使用したあなたのパスワードあるいはGAME.FUNDアカウントは、直ちに交換あなたのアカウントのパスワード。',
    server_page_p15 : 'プライバシーと著作権保護',
    server_page_p16 : 'GAME.FUNDのプライバシーを紹介した政策をお使いの私たちのサービスを、私たちはどのように処理するあなたの個人データとあなたのプライバシーを守る。私たちのサービスを使って表示さGAME.FUNDご同意に私たちのプライバシーを使ってあなたの個人データ政策。',
    server_page_p17 : '私たちは関連する法律の規定の流れに基づいて、著作権侵害の疑いの疑いに対して、何度も権利侵害者の口座を終了します。',
    server_page_p18 : '私達は著作権者に情報を提供して、彼らを助けるためにオンラインで自分の知的財産権を管理することを助けます。もしあなたは人ですか.お知らせしたい、連絡メール：info@game.fund助けを得る。',
    server_page_p19 : 'あなたが私たちのサービスで発表した内容',
    server_page_p20 : '私たちのいくつかのサービスはあなたがアップロード、提出、記憶、送信、または受信内容を許可します。あなたはその内容に対して所有する知的財産権の所有権を保留している。簡単に言えば、あなたの内容に属しています。',
    server_page_p21 : 'あなたは内容のアップロード、提出・メモリまたは送付を私たちのサービスや、私たちのサービスのアップロード、提出、ストレージ、送信内容や受信時、あなたをGAME.FUND一項のグローバルの許可を得て、許可GAMEFUND PTE.LTD .使用、ホスティング、ストレージ、コピー、改正、創建派生作品（例えば、私たちのためにあなたの内容をより良いと私たちのサービスを合わせて使用して翻訳、原作またはその他の変更は、ここから発生の作）、伝播、出版、公開プレゼンテーション、公開展示や特殊な内容を配る。あなたがこの許可に授与された権限は、運営、宣伝、そして私たちのサービスを改善するために、新しいサービスを開発することができます。この許可は私たちのサービスを使用することを停止した後に依然として有効です。いくつかのサービスはあなたにいくつかの方法を提供することができて、あなたがこのサービスの内容に提供することを訪問して削除することに用います。また、我々の一部のサービスでの条項や設定は、関連サービスに提出する内容の使用範囲を縮小することができます。私たちのサービスに関する内容については、この許可を与えてくれる必要がある権利を確保してください。',
    server_page_p22 : '私たちの自動化システムは、あなたの内容を含む（メール）を分析し、それによってご提供によりふさわしい個人の需要の製品カスタマイズ機能、例えば、広告などの検索結果。あなたの送信、受信、記憶の内容については、我々のシステムはこの分析を行います。',
    server_page_p23 : 'もしあなたはGAME.FUNDアカウントを持っている、我々は我々のサービスを含む（広告やその他の商業環境）で、表示様の個人資料姓名、個人資料写真やおGAME.FUNDたりとGAME.FUNDアカウントに関連する第三者の応用の上の執行を操作（例えば、＋1やご発表の評価と評論）。',
    server_page_p24 : '私たちのサービスに関するソフトウェア',
    server_page_p25 : 'もしあるサービスがダウンロードまたはダウンロード可能なソフトウェアをダウンロードすることを要求する場合、このソフトウェアは新しいバージョンまたは新しい機能が発売される場合、あなたの設備に自動的に更新される可能性がある。いくつかのサービスは自分で自動的に更新することを許可することができます。',
    server_page_p26 : 'GAMEFUND PTE.LTD .あなたのライセンス料の免除を、譲渡、非独占のグローバルな個人の許可なしに、ご使用許可はGAME.FUND提供の、を含むサービス中ソフト。この許可をあなただけを通じて本約款許可の使われ方はGAME.FUNDの提供するサービスをからの利益のために。あなたはコピー、修正、発表、または販売レンタルサービスやソフト含むいかなる部分を逆工事しようとしないまたは本ソフトウェアのソースコードを抽出しない限り、この制限あるいはあなたは法律で禁じられてGAME.FUNDの書面許可を得る。',
    server_page_p27 : 'オープンソースソフトウェアは私たちを大切に。私たちのサービスで使用されているソフトウェアは、オープンソースコードの許可によって提供されている可能性があります。開放源コードの許可の中の規定は明確に上述のいくつかの条項を覆すことができます。',
    server_page_p28 : 'サービスの修正と終了',
    server_page_p29 : '我々は常に私たちのサービスを変更し改善している。我々は、機能を増加または削除する可能性がありますが、いずれかのサービスを停止または停止する可能性があります。',
    server_page_p30 : '私たちのサービスをいつでも停止することはできません。GAME.FUNDもおそらく随時停止にご提供サービス、またはいつでも私達のサービスに増加、新たに設置しての制限。',
    server_page_p31 : '私たちはあなたが自分のデータの所有権を持って、このようなデータに対するアクセス権限を保留することが重要だと思います。もし私たちのあるサービスを停止し、合理的に可能な場合、私たちはユーザーに合理的な事前通知を出して、そしてユーザー情報サービスの中からチャンスを送金するが、第三者の発生のデータの変動と紛失（例えば：ゲームが止まって服など）を含まないで、GAME.FUNDのサービスの中で。',
    server_page_p32 : '保証と免除声明',
    server_page_p33 : 'サービスを提供する際には、ビジネスにおいて合理的なスキルや注意義務ができるようになりますので、ご利用のことをお好きになりたいと思います。しかし、サービスについての事項については、約束ができないことがあります。',
    server_page_p34 : '除本約款または付加条項に明確に定められたもののほか、GAMEFUND PTE.LTD .及び供給商と販売代理店サービスはいかなる具体的なコミットメント。例えば、私たちはサービス内容、サービスの具体的な機能、あるいはその信頼性、利用可能性、またはあなたの必要な能力に満足していない。サービスは「そのまま」で提供されている。',
    server_page_p35 : 'いくつかの司法の管轄区域を定めて特定の保証、例えば市販性、特定目的適用性や侵害の黙示保証。法律の許可の範囲内において,われわれはすべての保証を排除する。',
    server_page_p36 : 'サービスの責任',
    server_page_p37 : '法律の許す限り、GAMEFUND PTE.LTD .及び供給商と販売代理店を利益、収入の損害やデータ、財務損失または間接的に、特殊、結果性、懲戒性や懲罰的損害賠償の責任。',
    server_page_p38 : 'すべての情況の下で、GAMEFUND PTE.LTD .及び供給商と販売代理店、何な見通しや損害の責任を負わない損失。',
    server_page_p39 : '我々は、いくつかの国家/地域で理解している、あなたは消費者としていくつかの法定権利を有していることを理解します。もしあなたが個人の目的のためにサービスを使用するならば、契約を放棄することができない消費者の法定権利については、本条項または付加条項が制限されていない。',
    server_page_p40 : 'サービスのビジネス',
    server_page_p41 : 'もしあなたがある企業を代表して私たちのサービスを使用するなら、その企業は本条項を受け入れなければなりません。は、本サービス利用や違反本約款によるや関連のいかなる損害賠償訴訟を含んで、起訴されたり、クレーム、損失、損害賠償、起訴され、判決、訴訟費や弁護士費用発生のいかなる責任や費用、この企業の対応GAMEFUND PTE.LTD .とその関連機関、管理者、代理機構と従業員の損害賠償をする。',
    server_page_p42 : '本条項について',
    server_page_p43 : '我々は、他のサービスに適用される付加条項を修正することができ、例えば、法律の変更や我々のサービスの変化を反映するための修正を行うことができる。本条項を定期的に調べなければならない。私たちはこのページにこれらの条項の修正通知を公表することができます。私たちは適用されたサービスの中で付加条項の修正通知を公表することができます。すべての修正の適用はさかのぼる力を持っており、私たちが通知を出してその条項を廃止する限り。また、サービスの新しい機能に対する特別な修正や、法律の原因によって作成された修正は直ちに発効する。サービスの修正条項に同意しない場合は、サービスの使用を停止します。',
    server_page_p44 : '本約款の制約GAMEFUND PTE.LTD .あなたとの間の関係を創設し、かついかなる第三者受益権。',
    server_page_p45 : 'もしあなたがこの条項を守らないならば、私たちはすぐに行動を取ることができなくて、私たちが私たちが持っている可能性があるいかなる権利を放棄することを意味しない（例えば、将来行動をとる）。',
    server_page_p46 : 'もしある条項が強制的に実行できない場合、これは他の条項の効力に影響しない。',

    //邀请函
    invitation_page_title1 : 'ブロックチェーンに基づいたのグローバル',
    invitation_page_title3 : 'な分権化の人民所有人民管理人民享有のコ',
    invitation_page_title2 : 'ミュニティががあなたの加入を歓迎します',
    invitation_page_code : '招待コード',
    invitation_page_codetip : '資格獲得のページで招待コードを入力して、GAME.FUND',
    invitation_page_codetip1 : 'コミュニティに加入するの資格を獲得できます',
    press_code_tip : '招待コードをスキャンする',
    down_two_span : 'アカウントをお持ちの場合は、',

    reset_title_text: 'パスワードリセット',
    reset_ltitle_text1: '新しいパスワード',
    reset_ltitle_text2: 'パスワードの確認',
    reset_btn: 'を提出してください',
    resetpwd_success: 'パスワードリセット成功！',
    resetpwd_fail: 'パスワードのリセットが失敗した、もう一度お試してください！',

    //新变动 2-10
    code_date : '注意：有効期限は三日です、有効回数は一回',
    atop_half_text1 : '本コミュニティのプロモーション奨励政策により、お友達を招待して参加することを励まします。“45%内容インセンティブGF池”の中からお友達が実際に投資するの5％の等値GFを獲得できます。',
    r_country : '居住国や地域',
    whitelist_successful_confirm3 : '“45%内容インセンティブGF池”の中からお友達が実際に投資するの5％の等値GFを獲得できます',
    whitelist_successful_confirm2 : '友達を招待する ',
}